apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-channel-service2
  namespace: nimble-platform
  labels:
    app: nimble-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-channel-service2
  template:
    metadata:
      labels:
        app: data-channel-service2
    spec:
      containers:
        - name: data-channel-service2
          image: 'rannybal2024/data-channel-service:IMAGE_TAG'
          ports:
            - containerPort: 9099
              protocol: TCP
          env:
            - name: PORT
              value: '9098'
            - name: _JAVA_OPTIONS
              value: '-Xmx128m -Xms128m'
            - name: DATACHANNEL_DB_HOST
              value: kola-postgress-do-user-13910731-0.c.db.ondigitalocean.com
            - name: DATACHANNEL_DB_NAME
              value: datachanneldb?ssl=true&sslmode=require
            - name: DATACHANNEL_DB_USERNAME
              value: doadmin
            - name: DATACHANNEL_DB_PASSWORD
              value: AVNS_xN6h3TZAvlOwe4vdAdk
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: 'http://kafka:9092'
            - name: DATACHANNEL_DB_HOST_PORT
              value: '25060'
            - name: KAFKA_JAAS_CONFIG
            - name: CONFIG_SERVER_URI
              value: 'http://config-server:8888'
            - name: CONFIG_SERVER_FAILFAST
              value: 'true'
            - name: DISCOVERY_ENABLED
              value: 'true'
            - name: DISCOVERY_PREFER_IP
              value: 'false'
            - name: DISCOVERY_SERVER_URI
              value: 'http://service-discovery:8761'
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600